---
- name: Creating Confluent Hub Install Dir
  file:
    path: "{{kafka_connect_confluent_hub_client.install_dir}}"
    state: directory
    group: "{{kafka_connect_group}}"
    owner: "{{kafka_connect_user}}"
    mode: '764'
  
- name: Installing/Unarchiving Confluent Hub
  unarchive:
    src: "{{kafka_connect_confluent_hub_client.file}}"
    dest: "{{kafka_connect_confluent_hub_client.install_dir}}"
    remote_src: "{{kafka_connect_confluent_hub_client.is_remote}}"
    creates: "{{kafka_connect_confluent_hub_client.install_dir}}/bin/confluent-hub"

- name: Symlinking Confluent Hub CLI
  file:
    src: "{{kafka_connect_confluent_hub_client.install_dir}}/bin/confluent-hub"
    dest: "/usr/bin/confluent-hub"
    state: link
    
- name: "Installing Kafka Connect Connector(s) from Confluent Hub"
  shell: "{{kafka_connect_confluent_hub_client.install_dir}}/bin/confluent-hub install --no-prompt --component-dir {{kafka_connect_confluent_hub_plugins_dest}} {{item}}"
  with_items: "{{kafka_connect_confluent_hub_plugins}}"
  when: kafka_connect_confluent_hub_plugins|length > 0
  notify: restart connect distributed