---
- name: Wait for API to return 200 - HTTP
  uri:
    url: "http://localhost:{{kafka_connect_rest_port}}/connectors"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when: not kafka_connect_ssl_enabled|bool

- name: Wait for API to return 200 - HTTPS
  uri:
    url: "https://localhost:{{kafka_connect_rest_port}}/connectors"
    status_code: 200
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when: kafka_connect_ssl_enabled|bool
