- name: Kafka Connect Upgrade
  hosts: kafka_connect
  environment: "{{ proxy_env }}"
  serial: 1
  tasks:
    - import_role:
        name: confluent.variables_handlers

    - name: Get Package Facts
      package_facts:
        manager: auto

    - set_fact:
        confluent_server_enabled: true
      when: ansible_facts.packages['confluent-server'] is defined

    - set_fact:
        confluent_server_enabled: false
      when: ansible_facts.packages['confluent-kafka-2.12'] is defined

    - name: Set Current Package Version
      set_fact:
        # Choosing last package in kafka_connect_packages in case upgrade fails in middle of package installing
        kafka_connect_current_version: "{{ ansible_facts.packages['confluent-kafka-connect-replicator'][0]['version'] }}"

    - debug:
        msg: "Current version: {{kafka_connect_current_version}}   Upgrade to version: {{confluent_package_version}}"

    - name: Upgrade Kafka Connect
      include_tasks: tasks/upgrade_component.yml
      vars:
        service_name: "{{ kafka_connect_service_name }}"
        packages: "{{ kafka_connect_packages }}"
        backup_files:
          - "{{ kafka_connect.config_file }}"
          - "{{ kafka_connect.systemd_override }}"
        restore_files:
          - "{{ kafka_connect.config_file }}"
      when:
        - kafka_connect_current_version != confluent_full_package_version
        - kafka_connect_current_version != confluent_package_version

    - name: Wait for API to return 200 - HTTP
      uri:
        url: "http://localhost:{{kafka_connect_rest_port}}/connectors"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 5
      when: not kafka_connect_ssl_enabled|bool

    - name: Wait for API to return 200 - HTTPS
      uri:
        url: "https://localhost:{{kafka_connect_rest_port}}/connectors"
        status_code: 200
        validate_certs: no
      register: result
      until: result.status == 200
      retries: 60
      delay: 5
      when: kafka_connect_ssl_enabled|bool
