---
- name: Create SSL Certificate Generation Directory
  file:
    path: /var/ssl/private/generation
    state: directory
    mode: 0755

- name: Create CA
  shell: |
    openssl req -new -x509 \
      -keyout /var/ssl/private/generation/{{ssl_self_signed_ca_key_filename}} \
      -out /var/ssl/private/generation/{{ssl_self_signed_ca_cert_filename}} \
      -days 365 \
      -subj '/CN=ca1.test.confluent.io/OU=TEST/O=CONFLUENT/L=PaloAlto/S=Ca/C=US' \
      -passin pass:{{ssl_self_signed_ca_password}} -passout pass:{{ssl_self_signed_ca_password}}

- name: Copy Generated SSL Files Back to Ansible Host
  synchronize:
    src: /var/ssl/private/generation/
    dest: generated_ssl_files
    mode: pull
    use_ssh_args: yes

- name: Delete SSL Certificate Generation Directory
  file:
    path: /var/ssl/private/generation
    state: absent
