---
- name: Wait for webpage to serve HTTP content
  uri:
    url: "http://localhost:{{control_center_port}}"
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when:
    - not control_center_ssl_enabled|bool

- name: Wait for webpage to serve HTTPS content
  uri:
    url: "https://localhost:{{control_center_port}}"
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when:
    - control_center_ssl_enabled|bool
