---
- include_role:
    name: confluent.common
  when: not common_role_completed|bool

# Install Packages
- name: Install the Control Center Packages
  yum:
    name: "{{item}}{{confluent_package_redhat_suffix}}"
    state: latest
  loop: "{{control_center_packages}}"
  when: ansible_os_family == "RedHat"

- name: Install the Control Center Packages
  apt:
    name: "{{item}}{{confluent_package_debian_suffix}}"
  loop: "{{control_center_packages}}"
  when: ansible_os_family == "Debian"

# Configure environment
- name: Create Control Center Group
  group:
    name: "{{control_center.group}}"

- name: Create Control Center User
  user:
    name: "{{control_center.user}}"
    comment: "Control Center User"
    system: yes
    group: "{{control_center.group}}"

- include_role:
    name: confluent.ssl
  vars:
    truststore_storepass: "{{control_center_truststore_storepass}}"
    truststore_path: "{{control_center_truststore_path}}"
    keystore_path: "{{control_center_keystore_path}}"
    keystore_storepass: "{{control_center_keystore_storepass}}"
    keystore_keypass: "{{control_center_keystore_keypass}}"
    service_name: control_center
  when: control_center_ssl_enabled|bool or kafka_broker_listeners[control_center_kafka_listener_name]['ssl_enabled'] | default(ssl_enabled) | bool

- name: Configure Kerberos
  include_role:
    name: confluent.kerberos
  vars:
    kerberos_group: "{{control_center.group}}"
    kerberos_user: "{{control_center.user}}"
    kerberos_keytab_path: "{{control_center_kerberos_keytab_path}}"
    kerberos_handler: "restart control center"
  when: kafka_broker_listeners[control_center_kafka_listener_name]['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'GSSAPI'

- name: Create Control Center Config
  template:
    src: control-center.properties.j2
    dest: "{{control_center.config_file}}"
    mode: 0640
    owner: "{{control_center.user}}"
    group: "{{control_center.group}}"
  notify:
    - restart control center

- name: Create Logs Directory
  file:
    path: "{{control_center.appender_log_path}}"
    group: "{{control_center.group}}"
    owner: "{{control_center.user}}"
    mode: '764'
    recurse: yes

- name: Create Control Center log4j Config
  template:
    src: control-center_log4j.properties.j2
    dest: "{{control_center.log4j_file}}"
    mode: 0640
    owner: "{{control_center.user}}"
    group: "{{control_center.group}}"
  notify:
    - restart control center

- name: Create Service Override Directory
  file:
    path: "{{control_center.systemd_override | dirname}}"
    owner: "{{control_center.user}}"
    group: "{{control_center.group}}"
    state: directory
    mode: 0640

- name: Write Service Overrides
  template:
    src: override.conf.j2
    dest: "{{control_center.systemd_override}}"
    mode: 0640
    owner: "{{control_center.user}}"
    group: "{{control_center.group}}"
  notify:
    - reload systemd
    - restart control center

- name: Certs were Updated - Trigger Restart
  command: /bin/true
  notify: restart control center
  when: certs_updated|bool

- meta: flush_handlers

- name: Start Control Center Service
  systemd:
    name: "{{control_center_service_name}}"
    enabled: yes
    state: started

- name: Wait for webpage to serve HTTP content
  uri:
    url: "http://localhost:{{control_center_port}}"
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when:
    - not control_center_ssl_enabled|bool
    - health_checks_enabled|bool

- name: Wait for webpage to serve HTTPS content
  uri:
    url: "https://localhost:{{control_center_port}}"
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
  when:
    - control_center_ssl_enabled|bool
    - health_checks_enabled|bool
