---
- name: Wait for API to return 200 - HTTP
  uri:
    url: "http://localhost:{{ksql_listener_port}}/info"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when: not ksql_ssl_enabled|bool

- name: Wait for API to return 200 - HTTPS
  uri:
    url: "https://localhost:{{ksql_listener_port}}/info"
    status_code: 200
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when: ksql_ssl_enabled|bool
