---
- include_role:
    name: confluent.common
  when: not common_role_completed|bool

# Install Packages
- name: Install the KSQL Packages
  yum:
    name: "{{item}}{{confluent_package_redhat_suffix}}"
    state: latest
  loop: "{{ksql_packages}}"
  when: ansible_os_family == "RedHat"

- name: Install the KSQL Packages
  apt:
    name: "{{item}}{{confluent_package_debian_suffix}}"
  loop: "{{ksql_packages}}"
  when: ansible_os_family == "Debian"

# Configure environment
- name: Create Ksql Group
  group:
    name: "{{ksql.group}}"

- name: Create Ksql User
  user:
    name: "{{ksql.user}}"
    comment: "Connect Distributed User"
    system: yes
    group: "{{ksql.group}}"

- include_role:
    name: confluent.ssl
  vars:
    truststore_storepass: "{{ksql_truststore_storepass}}"
    truststore_path: "{{ksql_truststore_path}}"
    keystore_path: "{{ksql_keystore_path}}"
    keystore_storepass: "{{ksql_keystore_storepass}}"
    keystore_keypass: "{{ksql_keystore_keypass}}"
    service_name: ksql
  when: ksql_ssl_enabled|bool or kafka_broker_listeners[ksql_kafka_listener_name]['ssl_enabled'] | default(ssl_enabled) | bool

- name: Configure Kerberos
  include_role:
    name: confluent.kerberos
  vars:
    kerberos_group: "{{ksql.group}}"
    kerberos_user: "{{ksql.user}}"
    kerberos_keytab_path: "{{ksql_kerberos_keytab_path}}"
    kerberos_handler: "restart ksql"
  when: kafka_broker_listeners[ksql_kafka_listener_name]['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'GSSAPI'

- name: Change streams directory ownership
  file:
    path: "{{ksql_streams_state_dir}}"
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
    state: directory
    mode: 0750

- name: Create Ksql Config
  template:
    src: ksql-server.properties.j2
    dest: "{{ksql.config_file}}"
    mode: 0640
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
  notify:
    - restart ksql

- name: Create Logs Directory
  file:
    path: "{{ksql.appender_log_path}}"
    group: "{{ksql.group}}"
    owner: "{{ksql.user}}"
    mode: '764'
    recurse: yes

- name: Create Ksql log4j Config
  template:
    src: ksql-server_log4j.properties.j2
    dest: "{{ksql.log4j_file}}"
    mode: 0640
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
  notify:
    - restart ksql

- name: Ksql Jaas Config
  template:
    src: ksql-server_jaas.conf.j2
    dest: "{{ksql.jaas_file}}"
    mode: 0640
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
  when: kafka_broker_listeners[ksql_kafka_listener_name]['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'GSSAPI'
  notify:
    - restart ksql

- name: Create Service Override Directory
  file:
    path: "{{ksql.systemd_override | dirname}}"
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
    state: directory
    mode: 0640

- name: Write Service Overrides
  template:
    src: override.conf.j2
    dest: "{{ksql.systemd_override}}"
    mode: 0640
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
  notify:
    - reload systemd
    - restart ksql

- name: Certs were Updated - Trigger Restart
  command: /bin/true
  notify: restart ksql
  when: certs_updated|bool

- meta: flush_handlers

- name: Start Ksql Service
  systemd:
    name: "{{ksql_service_name}}"
    enabled: yes
    state: started

- name: Wait for API to return 200 - HTTP
  uri:
    url: "http://localhost:{{ksql_listener_port}}/info"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when:
    - not ksql_ssl_enabled|bool
    - health_checks_enabled|bool

- name: Wait for API to return 200 - HTTPS
  uri:
    url: "https://localhost:{{ksql_listener_port}}/info"
    status_code: 200
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when:
    - ksql_ssl_enabled|bool
    - health_checks_enabled|bool
