---
- name: Copy the client configuration file
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
  when: kerberos_configure|bool

- name: Create Keytabs Directory
  file:
    path: "{{kerberos.keytab_dir}}"
    state: directory
    group: "{{kerberos_group}}"
    mode: '650'

- name: Copy in Keytab File
  copy:
    src: "{{kerberos_keytab_path}}"
    dest: "{{kerberos.keytab_dir}}/{{kerberos_keytab_path | basename}}"
    owner: "{{kerberos_user}}"
    group: "{{kerberos_group}}"
    mode: '600'
  notify: "{{kerberos_handler}}"
