---
- name: Wait for Zookeeper Status
  shell: "{{zookeeper_health_check_command}}"
  args:
    executable: /bin/bash
  register: srvr
  until: srvr.rc == 0
  retries: 60
  delay: 5

- name: Wait for Zookeeper Quorum
  shell: "{{zookeeper_health_check_command}}"
  args:
    executable: /bin/bash
  register: srvr
  until: '"Latency min/avg/max:" in srvr.stdout'
  retries: 60
  delay: 5
